### ISSUE TITLE
EAC is on and i'm getting this message

### ISSUE THREAD

**Issue by SwagMLG345YT** [Ender-0001/CloudstorageEditor#2]
i've started it up and logged in but for some reason when i do i get this message

"Found a disallowed program running on machine, please disable [Custom Launcher] and reconnect."

i looked over to my task manager and EAC is running for some reason so could that something to do with it?
![Fortnite   2_15_2021 12_11_36 PM](https://user-images.githubusercontent.com/26439106/108025613-9e57b080-6fdb-11eb-968c-e55444bf6a09.png)

**Comment by Ender-0001** [comment]
Im Gonna Update the repo with a fix very soon
